development:
  secret_key_base: 'f94dac074d13a9ebdcb72f4f3bd2f3de51f7bb1704caa3bf363be0056721be4c7dd239e567e7184090d29caa4b901a27cd13f1e18ce4f4b5c5eca82a1a7d93c7'

test:
  secret_key_base: 'f94dac074d13a9ebdcb72f4f3bd2f3de51f7bb1704caa3bf363be0056721be4c7dd239e567e7184090d29caa4b901a27cd13f1e18ce4f4b5c5eca82a1a7d93c7'

production:
  secret_key_base: ''
